version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: support-postgres
    restart: always
    environment:
      POSTGRES_DB: support_db
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_pass
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: support-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pg_data:
